export_mapping:
  members:
    id:
      - id
    username:
      - username
    email:
      - email
  user_fields:
    matrnr: 1
    course_of_study: 2
    firstchoice: 3
    secondchoice: 4
    thirdchoice: 5
