plugins:
  user_fields_mapping:
    default: ''
    type: list
  export_user_members:
    default: ''
    type: list
  export_user_fields:
    default: ''
    type: list
  default_lecture_group:
    default: ''
    type: string
  active_lecture_groups:
    default: ''
    type: list
